services:
  # Serviço Web (Laravel/PHP via Docker)
  - type: web
    name: restaurant-tagline
    runtime: docker # O Render irá ler Dockerfile automaticamente
    envVars:
      - key: APP_NAME
        value: restaurant-tagline
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://restaurant-tagline.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromService:
          type: pserv
          name: restaurant-tagline-db
          property: host
      - key: DB_DATABASE
        value: cadastro_usuario

  - type: pserv
    name: restaurant-tagline-db
    runtime: image
    image:
      url: mysql:8.0
    plan: free
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
      - key: MYSQL_DATABASE
        value: cadastro_usuario

databases:
  - name: restaurant-tagline-db
    databaseName: cadastro_usuario
    plan: free