services:
  # Serviço Web (Laravel/PHP)
  - type: web
    name: restaurant-tagline
    runtime: php # Alterado para PHP para que ele execute o buildCommand
    buildCommand: composer install && npm install && npm run build
    startCommand: php artisan serve
    envVars:
      - key: APP_NAME
        value: restaurant-tagline
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://restaurant-tagline.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromService:
          type: pserv
          name: restaurant-tagline-db
          property: host
      - key: DB_DATABASE
        value: cadastro_usuario

  # Serviço de Banco de Dados (MySQL)
  - type: pserv
    name: restaurant-tagline-db
    runtime: image
    image: mysql:8.0 # Define qual imagem o Render deve baixar
    plan: free
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
      - key: MYSQL_DATABASE
        value: cadastro_usuario

databases:
  - name: restaurant-tagline-db
    databaseName: cadastro_usuario
    user: root