services:
  - type: web
    name: restaurant-tagline
    runtime: image
    buildCommand: composer install && npm install && npm run build
    startCommand: php artisan serve --host=0.0.0.0 --port=8080
    envVars:
      - key: APP_NAME
        value: restaurant-tagline
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://restaurant-tagline.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: CACHE_DRIVER
        value: redis

  - type: pserv
    name: restaurant-tagline-db
    runtime: mysql # image
    plan: free
    ipAllowList: []
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
      - key: MYSQL_DATABASE
        value: restaurant_db

databases:
  - name: restaurant-tagline-db
    databaseName: restaurant_db
    user: root